jobs:
test:
  override:
    - pip install -r requirements.txt
    - pybot -n non-critical -d "robot_results" ./TestSuite1.robot
workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "34 14 * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - test
   
