jobs:
   build:
       test:
          - pip install -r requirements.txt
          - pybot -n non-critical -d "robot_results" -o "../discard/output.xml" ./TestSuite1.robot
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "22 15 * * *"
          filters:
            branches:
              only: try-schedule-workflow

    jobs:
      - build
