version: 2
jobs:
  test:
    override:
       - pip install -r requirements.txt
       - pybot -n non-critical -d "robot_results" ./TestSuite1.robot
workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "40 13 * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - test
   
