jobs:
  job1:
     override:
       - date
       - pip install -r requirements.txt
       - pybot -n non-critical -d "robot_results" ./TestSuite1.robot
  general:
     artifacts:
        - "robot_results"
workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "43 13 * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - job1
