version: 2
jobs:
  test:
    override:
    - pip install -r requirements.txt
    - pybot -n non-critical -d "robot_results" -o "../discard/output.xml" ./selenium

workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "11 10 * * *"
          filters:
            branches:
              only:
                - master
                - beta
  build-and-validate:
    jobs:
      - test
