#test:
  #override:
   # - pip install -r requirements.txt
    #- pybot -n non-critical -d "robot_results" ./TestSuite1.robot
#general:
  #artifacts:
    #- "robot_results"
#workflows:
 # version: 2
  #hourly:
    #triggers:
      #- schedule:
          #cron: "40 13 * * *"
          #filters:
           # branches:
              #only:
               # - master
                #- beta
    #jobs:
      #- test
      
      
version: 2
jobs:
  test:
    steps:
      - run:
          name: test
          command: pip install -r requirements.txt
      - run:
          name: code-coverage
          command: pybot -n non-critical -d "robot_results" ./TestSuite1.robot   
workflows:
  version: 2
  hourly:
    triggers:
      - schedule:
          cron: "214* * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - test
   
